- CHANGELOG
- mrlegacy/src/main/java/org/apache/mahout/clustering/streaming/mapreduce/StreamingKMeansDriver.java
> MAHOUT-1639: streamingkmeans doesn't properly validate estimatedNumMapClusters -km

- CHANGELOG
- integration/src/main/java/org/apache/mahout/utils/clustering/JsonClusterWriter.java
> Mahout-1612: NullPointerException happens during JSON output format for clusterdumper

- flink/src/main/scala/org/apache/mahout/flinkbindings/FlinkEngine.scala
- flink/src/main/scala/org/apache/mahout/flinkbindings/blas/FlinkOpAewB.scala
- flink/src/main/scala/org/apache/mahout/flinkbindings/blas/FlinkOpAewScalar.scala
- flink/src/main/scala/org/apache/mahout/flinkbindings/blas/FlinkOpAt.scala
- flink/src/main/scala/org/apache/mahout/flinkbindings/blas/FlinkOpAtA.scala
- flink/src/main/scala/org/apache/mahout/flinkbindings/blas/FlinkOpAtB.scala
- flink/src/main/scala/org/apache/mahout/flinkbindings/blas/FlinkOpAx.scala
- flink/src/main/scala/org/apache/mahout/flinkbindings/blas/FlinkOpCBind.scala
- flink/src/main/scala/org/apache/mahout/flinkbindings/blas/FlinkOpMapBlock.scala
- flink/src/main/scala/org/apache/mahout/flinkbindings/blas/FlinkOpRBind.scala
- flink/src/main/scala/org/apache/mahout/flinkbindings/blas/FlinkOpRowRange.scala
- flink/src/main/scala/org/apache/mahout/flinkbindings/blas/FlinkOpTimesRightMatrix.scala
- flink/src/main/scala/org/apache/mahout/flinkbindings/drm/FlinkDrm.scala
- flink/src/test/scala/org/apache/mahout/flinkbindings/blas/LATestSuite.scala
- spark/src/main/scala/org/apache/mahout/sparkbindings/SparkEngine.scala
2. small renaming of methods in FlinkDrm.scala
> 1. Reworked FlinkEngine.drmDfsRead

- mr/src/main/java/org/apache/mahout/vectorizer/DictionaryVectorizer.java
Order and add missing paramters for createTermFrequencyVectors() javadoc parameter comments.
> MAHOUT-1836: reorder  javadoc  paramter comments

- README.md
And a shell Example.
Please Review @_MAHOUT
> [MAHOUT-1956] Update README.md to include build instructions for GPU/GPU/JVM

- buildtools/pom.xml
- distribution/pom.xml
- examples/pom.xml
- h2o/pom.xml
- hdfs/pom.xml
- integration/pom.xml
- math-scala/pom.xml
- math/pom.xml
- mr/pom.xml
- pom.xml
- spark/pom.xml
- viennacl-omp/pom.xml
- viennacl/pom.xml
manually rolling back 0.13.2 maven auto generated: `[preparation for next release iteration]`
> (NOJIRA) Manual rollback to 0.13.1-SNAPSHOT + cosmetic fixes

- website/general/mahout-benchmarks.md
> Fixed Spelling.

- buildtools/assembly/bin.xml
- buildtools/assembly/src.xml
- pom.xml
> HOTFIX: Source and binary assemblies

- core/pom.xml
- engine/hdfs/pom.xml
- engine/spark/pom.xml
- pom.xml
> HOTFIX: Adding JavaDocs functionality back in

- website/developers/how-to-release.md
> NOJIRA: Editing release instructions

- website/docs/latest/algorithms/regression/index.md
> WEBSITE-Typo in website title

- .github/PULL_REQUEST_TEMPLATE
- pom.xml
Update to latest RAT version 0.13
Does this change break earlier versions? n
Is this the beginning of a larger project for which a feature branch should be made? n
> MAHOUT-2067: Update RAT plugin to latest release version.

- pom.xml
Due to a merge error the changes already applied are gone.
see https://github.com/apache/mahout/pull/372
n
n
@andrewpalumbo fyi
> MAHOUT-2067: Latest RAT release, fixes in pom.xml

- distribution/pom.xml
- pom.xml
> Introduced the "with-community-modules" profile (disabled per default)

- community/mahout-mr/integration/src/main/java/org/apache/mahout/utils/nlp/collocations/llr/BloomTokenFilter.java
- community/mahout-mr/integration/src/test/java/org/apache/mahout/utils/nlp/collocations/llr/BloomTokenFilterTest.java
Remove usage of words "whitelist" to make project more welcoming to diverse set of potential contributors
No
No
> Fixes MAHOUT-2106 - Remove words "whitelist"

- community/mahout-mr/integration/src/main/java/org/apache/mahout/utils/nlp/collocations/llr/BloomTokenFilter.java
- community/mahout-mr/integration/src/test/java/org/apache/mahout/utils/nlp/collocations/llr/BloomTokenFilterTest.java
The renaming done under MAHOUT-2106 left the text of the comments somehow confusing. Let's have a better wording.
> MAHOUT-2106 Adjust confusing comments

- website/_config.yml
- website/_includes/analytics.html
- website/_includes/doc-navbar.html
- website/_includes/footer.html
- website/_includes/head.html
- website/_includes/navbar.html
- website/_includes/sidebar.html
- website/_layouts/default.html
- website/_layouts/doc-default.html
- website/_layouts/doc-page.html
- website/_layouts/home.html
- website/_layouts/page.html
- website/_layouts/post.html
- website/_posts/2017-12-20-new-website.md
- website/_posts/2018-06-18-preping-014.md
- website/_posts/2019-12-14-version-14-1.md
- website/assets/css/main.scss
- website/index.md
> [HOTFIX] Website issues

- website/general/books-tutorials-and-talks.md
- website/general/downloads.md
- website/general/faq.md
- website/general/glossary.md
- website/general/mahout-benchmarks.md
- website/general/mahout-wiki.md
- website/general/mailing-lists.md
- website/general/powered-by-mahout.md
- website/general/privacy-policy.md
- website/general/professional-support.md
- website/general/reference-reading.md
- website/general/release-notes.md
- website/general/who-we-are.md
> [HOTFIX] Missed a directory when pulling ASF headers off

- website/docs/latest/algorithms/clustering/distance-metrics.md
> MAHOUT-2127 Fix broken DistanceMetrics.scala hyperlink

- website/build_site.sh
In theory- this small little fix should build and publish the 14.1 docs. When we merge we'll see if that's true- if it is, then I will update the nav bar. 
- [/] Created unit tests where appropriate
- [/] Added licenses correct on newly added files
- [/] Added documentation in scala docs/java docs, and to website
- [/] Successfully built and ran all unit tests, verified that all tests pass locally.
> MAHOUT-2129 Update Version for docs [WEBISTE]

- website/_includes/doc-navbar.html
- website/_posts/2021-06-01-Zeppelin Quickstart.md
- website/docs/latest/quickstart.md
- [/] Created unit tests where appropriate
- [/] Added licenses correct on newly added files
- [/] Added documentation in scala docs/java docs, and to website
- [/] Successfully built and ran all unit tests, verified that all tests pass locally.
> MAHOUT-2133 Updated quickstart to reference Getting Started with Zeppelin

- docker/getting-started/Dockerfile
- website/_includes/doc-navbar.html
- website/_includes/navbar.html
- website/docs/latest/tutorials/misc/getting-started-with-zeppelin/index.md
- website/docs/latest/tutorials/misc/mahout-in-zeppelin/index.md
- [/] Created unit tests where appropriate
- [/] Added licenses correct on newly added files
- [/] Successfully built and ran all unit tests, verified that all tests pass locally.
> MAHOUT-2133 Pt 2

- core/src/main/scala/org/apache/mahout/math/algorithms/regression/CochraneOrcuttModel.scala
Add docs for the Cochrane Orcutt Regression
No
Maybe a 'clean up the docs' feature branch- to be discussed on list
> NOJIRA: Add docs for Cochrane Orcutt Regression

- core/src/main/scala/org/apache/mahout/math/algorithms/clustering/Canopy.scala
Add scaladocs for Canopy Cluster Algorithm
> MAHOUT-2147: Canopy Cluster Scaladocs

- core/src/main/scala/org/apache/mahout/math/algorithms/common/distance/DistanceMetrics.scala
Adding scaladocs to distance metrics
No
No
> MAHOUT-2148 Add scaladocs to distance metrics

- core/src/main/scala/org/apache/mahout/math/algorithms/preprocessing/AsFactor.scala
Add scaladocs to AsFactor.scala
No
No
> MAHOUT-2151 Add Scaladocs to AsFactor.scala

- core/src/main/java/org/apache/mahout/common/RandomWrapper.java
Add javadocs for RandomWrapper
> MAHOUT-2155 Add Javadocs for RandomWrapper

- website/_includes/footer.html
Per https://whimsy.apache.org/site/project/mahout this is required
> MAHOUT-2160 - Add asf link to footer

- website/_includes/sidebar.html
Fixes link (it did on my machine, but not sure why link wasn't working before soo may or may not actually fix)
> MAHOUT-2161Fix website link in sidebar

- pom.xml
Some how the RAT check to ignore JSON files got deleted. 
> 2139 - Ignore JSON in rat

- .github/workflows/mahout.yml
- [ X ] A JIRA ticket exists (if not, please create this first)[https://issues.apache.org/jira/browse/mahout/]
- [ X ] Title of PR is "MAHOUT-XXXX Brief Description of Changes" where XXXX is the JIRA number.
- [ X ] Created unit tests where appropriate
- [ X ] Added licenses correct on newly added files
- [ X ] Assigned JIRA to self
- [ X ] Added documentation in scala docs/java docs, and to website
- [ X ] Successfully built and ran all unit tests, verified that all tests pass locally.
Does this change break …
> MAHOUT-2149

- website/_papers/Quantum-Kernel-Estimation-With-Neutral-Atoms-For-Supervised-Classification.md
- website/_papers/Quantum-machine-learning-beyond-kernel-methods.md
These papers posts are in essence just unsolicited docs posts, so skipping the PR template
> Papers 3-6-24

- qumat/qumat.py
I don't know how i made such a mess of the config on the initial push, but this fixes it. 
Required to unblock #2199
no
no
> MAHOUT-2199 - Fix Config Loading

- examples/Simple_Example.ipynb
Provides a simple example notebook that will run in Colab
no
no
> MAHOUT-2198 Add Notebook Closes #2198

- website/_includes/navbar.html
- website/about/how-to-contribute.md
- website/community/mailing-lists.md
- website/documentation/developers/developer-resources.md
- website/documentation/developers/gsoc.md
- website/documentation/developers/how-to-update-the-website.md
- website/documentation/developers/index.md
- website/documentation/developers/issue-tracker.md
This PR fixes some broken links on the mahout website.
No
No
> First Set of Broken Website Links

- website/_includes/navbar.html
- website/documentation/developers/developer-resources.md
- website/documentation/developers/how-to-release.md
- website/documentation/developers/patch-check-list.md
This PR fixes some broken links on the mahout website.
No
No
> Last Set of Broken Website Links

- pyproject.toml
- qumat/cirq_backend.py
- qumat/qiskit_backend.py
- qumat/qumat.py
- requirements.txt
Adds the cirq backend and refactors qumat to allow for multiple backends.
Next steps: 
- implementing `execute` on qiskit and cirq
- examples
- docs
- tests (requires testing framework)
no
maybe if this was in prod, not POC, but it's poc, it _is_ the feature branch
> MAHOUT-2203 Add Cirq backend

- examples/Simple_Example.ipynb
- qumat/cirq_backend.py
- qumat/qiskit_backend.py
I suppose it really should be _fix_ the execute method. It works now.
No
No
> Mahout 2201 - Add execute method

- .github/workflows/mahout.yml
> MAHOUT 2212 - runs builds for pull requests against branch

- README.md
Add roadmap to readme.md
No
No
> MAHOUT-2211 Add Roadmap to Readme.md

- docs/api.md
This PR provides documentation for the initial implementation of Qumat
No
No
> Mahout 2210 Docs

- pyproject.toml
- qumat/amazon_braket_backend.py
Add amazon bracket backend.
no
maybe...
> MAHOUT-2213 Implement Amazon Bracket backend

- docs/api.md
- qumat/amazon_braket_backend.py
- qumat/cirq_backend.py
- qumat/qiskit_backend.py
- qumat/qumat.py
> MAHOUT-2209 Implement draw_circuit( method

- .github/ISSUE_TEMPLATE/issue_template.md
> MAHOUT-452 Create issue_template.md

- qumat/amazon_braket_backend.py
- qumat/cirq_backend.py
- qumat/qiskit_backend.py
- qumat/qumat.py
Adds rotational gates X, Y, Z, and U
assosciated issues: #464 #465 #466 #467 
> MAHOUT 464/5/6/7 - Add rotational gates

- website/_includes/analytics.html
Remove Google Analytics from the Mahout Website as per ASF Privacy Policy. Please see
https://issues.apache.org/jira/browse/MAHOUT-2215 for more details
Does this change break earlier versions? **No**
Is this the beginning of a larger project for which a feature branch should be made? **No**
> MAHOUT-2215 Remove Google Analytics from the Mahout Website

- website/_includes/analytics.html
I did this off the main, which I ought not, but whatever. 
> [hotfix] Add Matamo

- .github/workflows/notebook-testing.yml
- pyproject.toml
> MAHOUT-484 Pump to python 3.10

- website/Gemfile
- website/_config.yml
- website/_includes/head.html
- website/_includes/navbar.html
- website/general/books-tutorials-and-talks.md
- website/quantum-computing-primer/01_introduction/index.md
- website/quantum-computing-primer/03_qubits/index.md
- website/quantum-computing-primer/04_quantum_gates/index.md
- website/quantum-computing-primer/05_quantum_circuits/index.md
- website/quantum-computing-primer/06_quantum_entanglement/index.md
- website/quantum-computing-primer/07_quantum_algorithms/index.md
- website/quantum-computing-primer/08_quantum_error_correction/index.md
- website/quantum-computing-primer/09_applications/index.md
- website/quantum-computing-primer/10_advanced_topics/index.md
- website/quantum-computing-primer/index.md
Add a quantum computing primer to the website
> Add QC Primer

- website/_config.yml
- website/quantum-computing-primer/03_qubits/index.md
- website/quantum-computing-primer/04_quantum_gates/index.md
- website/quantum-computing-primer/07_quantum_algorithms/index.md
- website/quantum-computing-primer/10_advanced_topics/index.md
Fixes 95% of latex errors in quantum computing guide
Closes #487 
> MAHOUT-487 Fix mathjax/latex

- website/_includes/sidebar.html
> Add FOSDEM talk to website#494

- website/_sass/mahout/_heading.scss
- website/assets/css/main.scss
Fixes #499 
This PR fixes some layout issues on mobile devices.
No.
No.
> Fixes - Mahout Version Hidden and Table Overflow on Mobile Devices

- .github/scripts/checks/__init__.py
- .github/scripts/checks/general_review.py
- .github/scripts/review_pr.py
- .github/workflows/pr_review.yml
Adds Gofannon PR Reviewer Workflow
Closes #506 
Please mark each with an "x"  
A GitHub issue exists (if not, please create one) [https://github.com/apache/mahout/issues]  
If all of these items are not yet complete, but you still feel it is appropriate to open a PR, please open it as a **Draft PR** instead.  
Once all requirements are met, you can mark it as ready for review.
Does this PR introduce a breaking change?
Describe how you tested the changes.
> MAHOUT-506: Add gofannon PR Review

- .github/workflows/pr_review.yml
Describe what this PR does.
Add links to related issues.
- Closes #123 
- Related to #123  
Please mark each with an "x"  
A GitHub issue exists (if not, please create one) [https://github.com/apache/mahout/issues]  
If all of these items are not yet complete, but you still feel it is appropriate to open a PR, please open it as a **Draft PR** instead.  
Once all requirements are met, you can mark it as ready for review.
Does this PR introduce a breaking change?
Describe how you tested the changes.
> hotfix - drop poetry

- website/Gemfile
- website/README.md
I have added the steps to setup the website locally using jekyll. Hope this helps new contributors. I have made these changes in mahout/website/README.md which was empty.
> Added the documentation to setup the Project Locally

- docs/getting_started_with_qumat.md
Creates getting started guide
- Closes #525   
Please mark each with an "x"  
A GitHub issue exists (if not, please create one) [https://github.com/apache/mahout/issues]  
If all of these items are not yet complete, but you still feel it is appropriate to open a PR, please open it as a **Draft PR** instead.  
Once all requirements are met, you can mark it as ready for review.
Does this PR introduce a breaking change?
Describe how you tested the changes.
> MAHOUT-525: getting started with qumat

- website/community/who-we-are.md
Added my name as a committer in who-we-are section.
> Added my name as a committer in who-we-are

- website/community/who-we-are.md
Just a quick update of the Who We Are section of the website to reflect recent PMC changes.
> Updated Who We Are page with new PMC and chair information.
